# Generated by Django 3.2.5 on 2021-07-30 16:28

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth_exam', '0015_auto_20210730_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=unixtimestampfield.fields.UnixTimeStampField(default=0.0),
        ),
    ]
