# Generated by Django 3.2.5 on 2021-07-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_exam', '0016_alter_todo_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
